import Joi from "joi";

export const createCompanySchema = Joi.object({
   company_name: Joi.string().min(1).max(255).required(),
   company_email: Joi.string().email().max(255).optional(),
   company_phone: Joi.string().max(25).optional(),
   company_fax: Joi.string().max(20).optional(),
   company_website: Joi.string().uri().max(255).optional(),
   address_line1: Joi.string().max(255).optional(),
   address_line2: Joi.string().max(255).optional(),
   address_line3: Joi.string().max(255).optional(),
   city: Joi.string().max(100).optional(),
   state: Joi.string().max(100).optional(),
   state_code: Joi.string().max(10).optional(),
   country: Joi.string().max(100).optional(),
   pincode: Joi.string().max(20).optional(),
   gstin: Joi.string().length(15).uppercase().optional(),
   pan: Joi.string().length(10).uppercase().optional(),
   cin: Joi.string().length(21).uppercase().optional(),
   contact_person_name: Joi.string().max(255).optional(),
   contact_person_email: Joi.string().email().max(255).optional(),
   contact_person_phone: Joi.string().max(25).optional(),
   taxpayer_type: Joi.string().optional(),
   logo: Joi.string().max(255).optional(),
});

export const updateCompanySchema = Joi.object({
   company_name: Joi.string().min(1).max(255).optional().allow("", null),
   company_email: Joi.string().email().max(255).optional().allow("", null),
   company_phone: Joi.string().max(25).optional().allow("", null),
   company_fax: Joi.string().max(20).optional().allow("", null),
   company_website: Joi.string().uri().max(255).optional().allow("", null),
   address_line1: Joi.string().max(255).optional().allow("", null),
   address_line2: Joi.string().max(255).optional().allow("", null),
   address_line3: Joi.string().max(255).optional().allow("", null),
   city: Joi.string().max(100).optional().allow("", null),
   state: Joi.string().max(100).optional().allow("", null),
   state_code: Joi.string().max(10).optional().allow("", null),
   country: Joi.string().max(100).optional().allow("", null),
   pincode: Joi.string().max(20).optional().allow("", null),
   gstin: Joi.string().length(15).uppercase().optional().allow("", null),
   pan: Joi.string().length(10).uppercase().optional().allow("", null),
   cin: Joi.string().length(21).uppercase().optional().allow("", null),
   contact_person_name: Joi.string().max(255).optional().allow("", null),
   contact_person_email: Joi.string().email().max(255).optional().allow("", null),
   contact_person_phone: Joi.string().max(25).optional().allow("", null),
   taxpayer_type: Joi.string().optional().allow(null),
   logo: Joi.string().max(255).optional().allow("", null),
   is_active: Joi.boolean().optional().allow(null),
}).min(1); // At least one field must be provided for update
``